WahanaTest/Areas/Admin/Models/Barang.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Penjualan.Areas.Admin.Models
{
    public class Barang
    {

        public int id { get; set; }

        public string nama { get; set; }

        public string sales_price { get; set; }

        public string id_satuan { get; set; }
        public string satuan { get; set; }


        public DateTime? created_at { get; set; }

        public string created_by { get; set; }

        public DateTime? updated_at { get; set; }

        public string updated_by { get; set; }

    }
}

WahanaTest/Areas/Admin/Controllers/BarangController.cs
using Penjualan.Helper;
using Penjualan.Service;
using Penjualan.Service.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using DataTables.Mvc;
using System.Threading.Tasks;
using Penjualan.Areas.Admin.Models;

namespace Penjualan.Areas.Admin.Controllers
{
    public class BarangController : Controller
    {
        private GeneralHelper dHelper = new GeneralHelper();
        private readonly IBarang barang;

        public BarangController() : this(new BarangService()) { }
        public BarangController(IBarang barang)
        {
            this.barang = barang;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetList([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {
            var query = barang.Get().AsQueryable();

            var totalCount = query.Count();

            #region Filtering
            // Apply filters for searching
            if (requestModel.Search.Value != string.Empty)
            {
                var value = requestModel.Search.Value.Trim();
                query = query.Where(p => p.nama.ToLower().ToString().Contains(value.ToString().ToLower()) ||
                                         p.sales_price.ToLower().ToString().Contains(value.ToString().ToLower()) ||
                                         p.id_satuan.ToLower().ToString().Contains(value.ToString().ToLower())
                                    );
            }

            var filteredCount = query.Count();

            #endregion Filtering

            #region Sorting
            // Sorting
            var sortedColumns = requestModel.Columns.GetSortedColumns();
            var orderByString = String.Empty;

            foreach (var column in sortedColumns)
            {
                orderByString += orderByString != String.Empty ? "," : "";
                orderByString += (column.Data) + (column.SortDirection == Column.OrderDirection.Ascendant ? " asc" : " desc");
            }

            query = query.OrderBy(orderByString == string.Empty ? "username asc" : orderByString);

            #endregion Sorting

            // Paging
            query = query.Skip(requestModel.Start).Take(requestModel.Length);

            var data = query.Select(barang => new
            {
                barang.id,
                barang.nama,
                barang.sales_price,
                barang.id_satuan,
                barang.satuan,
                barang.created_at
            }).ToList();

            return Json(new DataTablesResponse(requestModel.Draw, data, filteredCount, totalCount), JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Add(Barang model)
        {
            bool isSave = false;
            try
            {

                model.created_by = dHelper.CurrentLoginUser();
                await barang.Add(model);

             
                var data = barang.GetRow(model.nama);
                if (data == null || data.id == 0)
                {
                    await barang.Add(model);

                    isSave = true;
                    return Json(new { success = isSave, message = "Simpan Data Berhasil" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = isSave, message = "Barang sudah terdaftar" }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {

                return Json(new { success = isSave, message = "Simpan Data Gagal " + ex.Message }, JsonRequestBehavior.AllowGet);

            }

        }

        public async Task<ActionResult> Delete(int id)
        {
            bool isSave = false;
            try
            {

                await barang.Delete(id);

                isSave = true;
                return Json(new { success = isSave, message = "Update Data Berhasil" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {

                return Json(new { success = isSave, message = "Update Data Gagal " + ex.Message }, JsonRequestBehavior.AllowGet);

            }

        }

    }
}

WahanaTest/Areas/Admin/Controllers/UsersController.cs
using Penjualan.Helper;
using Penjualan.Service;
using Penjualan.Service.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using DataTables.Mvc;
using System.Threading.Tasks;
using Penjualan.Areas.Admin.Models;

namespace Penjualan.Areas.Admin.Controllers
{
    public class UsersController : Controller
    {
        private GeneralHelper dHelper = new GeneralHelper();
        private readonly IUsers user;

        public UsersController() : this(new UserService()) { }
        public UsersController(IUsers user)
        {
            this.user = user;
        }
        // GET: Admin/Users
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetList([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {
            var query = user.Get().AsQueryable();

            var totalCount = query.Count();

            #region Filtering
            // Apply filters for searching
            if (requestModel.Search.Value != string.Empty)
            {
                var value = requestModel.Search.Value.Trim();
                query = query.Where(p => p.username.ToLower().ToString().Contains(value.ToString().ToLower()) ||
                                         p.email.ToLower().ToString().Contains(value.ToString().ToLower()) ||
                                         p.phone.ToLower().ToString().Contains(value.ToString().ToLower())
                                    );
            }

            var filteredCount = query.Count();

            #endregion Filtering

            #region Sorting
            // Sorting
            var sortedColumns = requestModel.Columns.GetSortedColumns();
            var orderByString = String.Empty;

            foreach (var column in sortedColumns)
            {
                orderByString += orderByString != String.Empty ? "," : "";
                orderByString += (column.Data) + (column.SortDirection == Column.OrderDirection.Ascendant ? " asc" : " desc");
            }

            query = query.OrderBy(orderByString == string.Empty ? "username asc" : orderByString);

            #endregion Sorting

            // Paging
            query = query.Skip(requestModel.Start).Take(requestModel.Length);

            var data = query.Select(user => new
            {   
                user.username,
                user.email,
                user.phone,
                user.created_at
            }).ToList();

            return Json(new DataTablesResponse(requestModel.Draw, data, filteredCount, totalCount), JsonRequestBehavior.AllowGet);
        }
        public async Task<ActionResult> Add(Users model)
        {
            bool isSave = false;
            try
            {

                model.created_by = dHelper.CurrentLoginUser();

                var data = user.GetRow(model.created_by);
                if (data == null)
                {
                    await user.Add(model);
               
                    isSave = true;
                    return Json(new { success = isSave, message = "Simpan Data Berhasil" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = isSave, message = "Username sudah terdaftar" }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {

                return Json(new { success = isSave, message = "Simpan Data Gagal " + ex.Message }, JsonRequestBehavior.AllowGet);

            }

        }
        public async Task<ActionResult> Edit(Users model)
        {
            bool isSave = false;
            try
            {

                model.updated_by = dHelper.CurrentLoginUser();
                await user.Edit(model);

                isSave = true;
                return Json(new { success = isSave, message = "Update Data Berhasil" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {

                return Json(new { success = isSave, message = "Update Data Gagal " + ex.Message }, JsonRequestBehavior.AllowGet);

            }

        }

        public async Task<ActionResult> Delete(string username)
        {
            bool isSave = false;
            try
            {
                if (username.ToLower() == "admin")
                {
                    return Json(new { success = isSave, message = "Admin tidak boleh di hapus" }, JsonRequestBehavior.AllowGet);
                }
                await user.Delete(username);

                isSave = true;
                return Json(new { success = isSave, message = "Hapus Data Berhasil" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {

                return Json(new { success = isSave, message = "Hapus Data Gagal " + ex.Message }, JsonRequestBehavior.AllowGet);

            }

        }
    }
}

WahanaTest/Areas/Admin/Views/Barang/Index.cshtml
@using Penjualan.Areas.Admin.Models
@{
    ViewBag.Title = "LIST Barang";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Barang
        </h1>
        <ol class="breadcrumb">
            <li><a href="/admin/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">User</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div id="tablegrid">
            @Html.Partial("_ListBarang")
        </div>
    </section>
</div>

<div class="modal fade" id="_popUp" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content panel-primary">
            <div class="panel-heading">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title" id="_title"></h2>
            </div>
            <div class="modal-body">
                @*<h4 style="color:red;" class="hidden" id="_delConfirm">Are your sure delete this data?</h4>*@
                <div class="form-horizontal">
                    <input id="_inputState" class="form-control hidden" />
                    <div class="form-group">
                        <label class="col-sm-3 col-md-4 control-label" style="text-align:left;">Nama</label>
                        <label class="col-sm-1 col-md-1 control-label">:</label>
                        <div class="col-sm-8 col-md-7">
                            <input id="nama" class="form-control" autofocus />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-4 control-label" style="text-align:left;">Sales Price</label>
                        <label class="col-sm-1 col-md-1 control-label">:</label>
                        <div class="col-sm-8 col-md-7">
                            <input id="sales_price" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 col-md-4 control-label" style="text-align:left;">Satuan</label>
                        <label class="col-sm-1 col-md-1 control-label">:</label>
                        <div class="col-sm-8 col-md-7">
                            <input id="id_satuan" class="form-control" />
                        </div>
                    </div>

                    <div class="form-group hidden">
                        <label class="col-sm-3 col-md-4 control-label" style="text-align:left;">id</label>
                        <label class="col-sm-1 col-md-1 control-label">:</label>
                        <div class="col-sm-8 col-md-7">
                            <input id="id" class="form-control" />
                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="_saveBtn" class="btn btn-primary" onclick="return ProsesData()" style="width:100px">Simpan</button>&nbsp;
                <button type="button" class="btn btn-primary" data-dismiss="modal" style="width:100px">Kembali</button>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>
        $(document).ready(function () {
            DataTable();
            var menuItem = $('#left-sidebar-menu-master');
            menuItem.addClass('active');
            var subMenuItem = menuItem.find('#master-barang');
            subMenuItem.addClass('active');
        })
        var nama;
        var sales_price;
        var id_satuan;
        var id;

        function ClearVar() {
            nama = "";
            sales_price = "";
            id_satuan = "";
            id = "";
        }
        function Init() {
            ClearVar();
            $("#nama").val("");
            $("#sales_price").val("");
            $("#id_satuan").val("");
            $("#id").val("")
            //$("#_satuan").val("").trigger('change');
        }

        var ListVM;
        function DataTable() {
            ListVM = {
                dt: null,

                init: function () {
                    dt = $('#tbBarang').DataTable({
                        "serverSide": true,
                        "processing": true,
                        "autoWidth": false,
                        "ajax": {
                            "url": "@Url.Action("GetList", "barang")",
                            //"url": "/users",
                            "type": 'POST',
                    },
                        "columns": [
                            { "title": "No", "data": "null", "searchable": false, "width": "20px" },
                            {
                                data: "id", "width": "80x", title: "Action", "orderable": false, "render": function (data, type, row) {
                                    return '<button id="btnEdit" class="btn btn-xs btn-primary" title="Edit" style="margin-right:5px"> <span class="fa fa-pencil"></span></button>' +
                                            '<button id="btnDelete" class="btn btn-xs btn-danger" title="Delete" "style="margin-right:5px"><span class="fa fa-trash"></span></button>';
                                }
                            },
                            { "title": "Id", "data": "nama", "searchable": true, visible:false },
                            { "title": "Nama Barang", "data": "nama", "searchable": true },
                            { "title": "Sales Price", "data": "sales_price", "searchable": true },
                            //{ "title": "Satuan", "data": "Satuan", "searchable": true},
                            { "title": "Created Date", "data": "created_at", "searchable": false, visible:false }

                        ],
                        columnDefs: [
                             {
                                 "targets": 0,
                                 "searchable": false,
                                 "orderable": false,
                                 "data": null,
                                 "title": 'No.',
                                 "render": function (data, type, full, meta) {
                                     return meta.settings._iDisplayStart + meta.row + 1;
                                 }
                             },
                        ],
                        "lengthMenu": [[10, 25, 50, 100], [10, 25, 50, 100]]
                    });
                    dt.on('order.dt search.dt', function () {
                        dt.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                            cell.innerHTML = i + 1;
                        });
                    }).draw();
                }
            }

        // initialize the datatables
            ListVM.init();


        }

        toastr.options = {
            "positionClass": "toast-top-center",
            "timeOut": "1000",
            "preventDuplicates": true,
            "closeButton": true,
            "progressBar": true
        }

        function Add() {
            Init();
            ClearVar();

            $("#_popUp").modal({ backdrop: 'static' });
            $("#_title").text("New Data");
            $("#_inputState").val("Create");

            $("#nama").removeAttr("disabled");
            $("#sales_price").removeAttr("disabled");
            $("#id_satuan").removeAttr("disabled");

            $("#_saveBtn").removeClass("hidden");
            $("#_saveBtn").html("Simpan");
            $('#_popUp').on('shown.bs.modal', function () {
                $('#nama').focus();
            })
        }
        $(document).on('click', '#btnEdit', function (event) {
            event.preventDefault();
            var row = $(this).closest('tr');
            var data = $('#tbUser').dataTable().fnGetData(row);
            Init();

            $("#_popUp").modal({ backdrop: 'static' });
            $('#_title').text("Edit Barang");

            $("#nama").val(data.nama);
            $("#sales_price").val(data.sales_price);
            $("#id_satuan").val(data.id_satuan);
            $("#id").val(data.id);

            $("#_inputState").val("Edit");

            $("#nama").attr("disabled", "disabled");
            $("#sales_price").removeAttr("disabled", "disabled");
            $("#id_satuan").removeAttr("disabled", "disabled");

            $("#_saveBtn").removeClass("hidden");
            $("#_saveBtn").html("Update");
            $('#_popUp').on('shown.bs.modal', function () {
                $('#email').focus();
            })
        });

        $(document).on('click', '#btnDelete', function (event) {
            event.preventDefault();
            var row = $(this).closest('tr');
            var data = $('#tbBarang').dataTable().fnGetData(row);
            Init();

            id = data.id;

            $("#_popUp").modal({ backdrop: 'static' });
            $('#_title').text("Hapus User");

            $("#id").val(data.id);
            $("#nama").val(data.nama);
            $("#sales_price").val(data.sales_price);
            $("#id_satuan").val(data.id_satuan);

            $("#_inputState").val("Delete");

            $("#nama").attr("disabled", "disabled");
            $("#sales_price").attr("disabled", "disabled");
            $("#id_satuan").attr("disabled", "disabled");

            $("#_saveBtn").removeClass("hidden");
            $("#_saveBtn").html("Hapus");
        });


        function ProsesData() {
            var InputState = $('#_inputState').val();
            ClearVar();
            nama = $("#nama").val();
            sales_price = $("#sales_price").val();
            id_satuan = $('#id_satuan').val();
            id = $("#id").val();


            if (InputState == "Create") {
                if (nama == "") {
                    toastr.warning("nama.")
                    $("#nama").focus();
                } else if (sales_price == "") {
                    toastr.warning("sales_price.")
                    $("#sales_price").focus();
                } else if (id_satuan == "") {
                    toastr.warning("id_satuan.")
                } else {
                    Create();
                }
            } else if (InputState == "Edit") {
                ValidasiEdit();
            } else if (InputState == "Delete") {
                Delete();
            }
        }


        function Create() {
            var model = {
                nama: nama,
                sales_price: sales_price,
                id_satuan: id_satuan
            }
            $.ajax({
                type: "POST",
                url: '@Url.Action("Add", "barang")',
                data: {
                    model : model
                },
                success: function (data) {
                    if (data.success) {
                        toastr.success(data.message);
                        $("#_popUp").modal('hide');
                        Init();
                        $('#tbBarang').DataTable().ajax.reload();
                    } else {
                        toastr.error(data.message);
                        //$("#_popUp").modal('hide');
                        //Init();
                    }
                },
            });
        }

        function ValidasiEdit() {
            if (username == "") {
                toastr.warning("Isi Username.")
                $("#username").focus();
            } else if (email == "") {
                toastr.warning("Isi email.")
                $("#email").focus();
            } else {
                Edit();
            }
        }

        function Edit() {
            var model = {
                username: username,
                email: email,
                password: password,
                phone: phone
            }
            $.ajax({
                type: "POST",
                url: '@Url.Action("Edit", "Users")',
                data: {
                    model : model
                },
                success: function (data) {
                    if (data.success) {
                        toastr.success(data.message);
                        $("#_popUp").modal('hide');
                        Init();
                        $('#tbUser').DataTable().ajax.reload();
                    } else {
                        toastr.error(data.message);
                        $("#_popUp").modal('hide');
                        Init();
                    }
                },
            });
        }

        function Delete() {
            if (nama == "") {
                toastr.warning("Tidak ada data yang dihapus.")
            }
            else {
                alert(id);
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete", "Barang")',
                    data: {
                        id: id
                    },
                    success: function (data) {
                        if (data.success) {
                            toastr.success(data.message);
                            $("#_popUp").modal('hide');
                            Init();
                            $('#tbBarang').DataTable().ajax.reload();
                        } else {
                            toastr.error(data.message);
                            $("#_popUp").modal('hide');
                            Init();
                        }
                    },
                });
            }
        }


    </script>
}

WahanaTest/Areas/Admin/Views/Barang/_ListBarang.cshtml
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-body">
                <button type="button" class="btn btn-primary" onclick="return Add()"><span class="bold fa fa-plus"></span>&nbsp;&nbsp;Create New</button>
                <hr />

                <table class="table table-bordered table-striped table-condensed table-responsive table-hover" id="tbBarang"></table>
            </div>
        </div>
    </div>
</div>